services:
  - type: web
    name: flashget-api
    runtime: node
    rootDir: server
    buildCommand: npm install && pip install --upgrade yt-dlp
    startCommand: node index.js
    plan: free

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: YTDLP_PATH
        value: yt-dlp

    autoDeploy: true
