services:
  - type: web
    name: flashget-downloader-api-v2
    runtime: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: free

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: YTDLP_PATH
        value: yt-dlp

    autoDeploy: true
